apiVersion: fleet.cattle.io/v1alpha1
kind: HelmApp
metadata:
  name: azure-ccm
spec:
  helm:
    releaseName: cloud-provider-azure
    repo: https://raw.githubusercontent.com/kubernetes-sigs/cloud-provider-azure/master/helm/repo
    chart: cloud-provider-azure
  insecureSkipTLSVerify: true
  targets:
  - clusterSelector:
      matchLabels:
        cloud-provider: azure
