apiVersion: rollout.turtles-capi.cattle.io/v1alpha1
kind: ClusterUpgradeGroup
metadata:
  name: clusterupgradegroup-sample1
  annotations:
    cc-time: 2024-03-07T10:00:00Z
spec:
  className: quick-start-v1
  targets:
    - name: target-cluster3
      clusterName: cluster3
      doNotDeploy: false
    - name: target-cluster4
      clusterName: cluster4
      doNotDeploy: false
