apiVersion: rollout.turtles-capi.cattle.io/v1alpha1
kind: ClusterUpgradeGroup
metadata:
  name: clusterupgradegroup-sample2
  annotations:
    cc-time: 2024-03-07T09:00:00Z
spec:
  className: quick-start-v1
  targets:
    - name: target-cluster1
      clusterName: cluster1
      doNotDeploy: false
