{{- if index .Values "cluster-api-operator" "cluster-api" "enabled" }}
---
apiVersion: v1
kind: Namespace
metadata:
  annotations:
    "helm.sh/hook": "post-install, post-upgrade"
    "helm.sh/hook-weight": "1"
  name: {{ index .Values "cluster-api-operator" "cluster-api" "core" "namespace" }}
---
apiVersion: operator.cluster.x-k8s.io/v1alpha1
kind: CoreProvider
metadata:
  name: cluster-api
  namespace: {{ index .Values "cluster-api-operator" "cluster-api" "core" "namespace" }}
  annotations:
    "helm.sh/hook": "post-install, post-upgrade"
    "helm.sh/hook-weight": "2"
spec:
  version: {{ index .Values "cluster-api-operator" "cluster-api" "version" }}
  additionalManifests:
    name: capi-additional-resources
    namespace: {{ index .Values "cluster-api-operator" "cluster-api" "core" "namespace" }}
{{- if and (index .Values "cluster-api-operator" "cluster-api" "configSecret" "name") (index .Values "cluster-api-operator" "cluster-api" "configSecret" "namespace") }}
  secretName: {{ index .Values "cluster-api-operator" "cluster-api" "configSecret" "name" }}
  secretNamespace: {{ index .Values "cluster-api-operator" "cluster-api" "configSecret" "namespace" }}
{{ else }}
  secretName: {{ index .Values "cluster-api-operator" "cluster-api" "configSecret" "defaultName" }}
  secretNamespace: {{ index .Values "cluster-api-operator" "cluster-api" "core" "namespace" }}
{{- end }}
{{- if or (index .Values "cluster-api-operator" "cluster-api" "core" "fetchConfig" "url") (index .Values "cluster-api-operator" "cluster-api" "core" "fetchConfig" "selector") }}
  fetchConfig:
    {{- if index .Values "cluster-api-operator" "cluster-api" "core" "fetchConfig" "url" }}
    url: {{ index .Values "cluster-api-operator" "cluster-api" "core" "fetchConfig" "url" }}
    {{- end }}
    {{- if index .Values "cluster-api-operator" "cluster-api" "core" "fetchConfig" "selector" }}
    selector: {{ index .Values "cluster-api-operator" "cluster-api" "core" "fetchConfig" "selector" }}
    {{- end }}
{{- end }}
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: capi-additional-resources
  namespace: {{ index .Values "cluster-api-operator" "cluster-api" "core" "namespace" }}
  annotations:
    "helm.sh/hook": "post-install, post-upgrade"
    "helm.sh/hook-weight": "2"
data: 
  manifests: |-
    apiVersion: rbac.authorization.k8s.io/v1
    kind: ClusterRole
    metadata:
      name: provisioning-rke-cattle-io
      labels:
        cluster.x-k8s.io/aggregate-to-manager: "true"
    rules:
      - apiGroups: ["rke.cattle.io"]
        resources: ["*"]
        verbs: ["*"]
    ---
    apiVersion: rbac.authorization.k8s.io/v1
    kind: ClusterRole
    metadata:
      name: provisioning-rke-machine-cattle-io
      labels:
        cluster.x-k8s.io/aggregate-to-manager: "true"
    rules:
      - apiGroups: ["rke-machine.cattle.io"]
        resources: ["*"]
        verbs: ["*"]
{{- if .Values.rancherTurtles.disableEmbeddedCAPI }}
    ---
    apiVersion: management.cattle.io/v3
    kind: Feature
    metadata:
      name: embedded-cluster-api
    spec:
      value: false
{{- end }}
---
{{- if not (and (index .Values "cluster-api-operator" "cluster-api" "configSecret" "name") (index .Values "cluster-api-operator" "cluster-api" "configSecret" "namespace")) }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ index .Values "cluster-api-operator" "cluster-api" "configSecret" "defaultName" }}
  namespace: {{ index .Values "cluster-api-operator" "cluster-api" "core" "namespace" }}
  annotations:
    "helm.sh/hook": "post-install, post-upgrade"
    "helm.sh/hook-weight": "2"
type: Opaque
stringData:
  CLUSTER_TOPOLOGY: "true"
  EXP_CLUSTER_RESOURCE_SET: "true"
  EXP_MACHINE_POOL: "true"
{{- end }}
{{- end }}
