name: "Build release"
description: "Builds release image and pushes to the registry"
inputs:
  arch:
    description: "Architecture of the built image"
    required: true
    type: string
  tag:
    description: "Image tag"
    type: string
    default: "github-actions"
  org:
    description: "Organization part of the image path"
    required: false
    default: "rancher-sandbox"
    type: string
  registry:
    description: "The registry to login"
    required: true
    type: string
  username:
    description: "The username to registry"
    required: true
    type: string
  password:
    required: true
    description: "The password for registry login"
    type: string
outputs:
  image:
    description: "Full image name"
    value: ${{ steps.image_info.outputs.image_name }}
  digest:
    description: "Image digest"
    value: ${{ steps.image_info.outputs.digest }}

runs:
  using: "composite"
  steps:
    - name: setupGo
      uses: actions/setup-go@v4
      with:
        go-version: "=1.20.7"
    - name: Docker login to ghcr registry
      uses: docker/login-action@v3
      with:
        registry: ${{ inputs.registry }}
        username: ${{ inputs.username }}
        password: ${{ inputs.password }}
    - name: Build docker image
      shell: bash
      run: make docker-build-${{ inputs.arch }} TAG=${{ inputs.tag }} REGISTRY=${{ inputs.registry }} ORG=${{ inputs.org }}
    - name: Push docker image to registry
      shell: bash
      run: make docker-push-${{ inputs.arch }} TAG=${{ inputs.tag }} REGISTRY=${{ inputs.registry }} ORG=${{ inputs.org }}
    - name: Store image and digest
      shell: bash
      id: image_info
      run: |
        out=$( docker images --digests --format "{{.Digest}} {{.Repository}}" | head -1 )
        echo "digest=${out% *}" >> $GITHUB_OUTPUT
        echo "image_name=${out#* }" >> $GITHUB_OUTPUT
