name: dependabot

on:
  pull_request:
    types: [opened, edited, synchronize, reopened, labeled, unlabeled]
    branches:
      - dependabot/**
  push:
    branches:
      - dependabot/**
  workflow_dispatch:

permissions:
  contents: write # Allow to update the PR.

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
    - name: Set up Go 1.x
      uses: actions/setup-go@6edd4406fa81c3da01a34fa6f6343087c207a568 # tag=v3.5.0
      with:
        go-version: 1.22.0
      id: go
    - name: Check out code into the Go module directory
      uses: actions/checkout@1d96c772d19495a3b5c517cd2bc0cb401ea0529f # tag=v4.1.3
    - name: Update generated code
      run: make generate
    - name: Commit changes
      run: |
        git config --local user.email "49699333+dependabot[bot]@users.noreply.github.com"
        git config --local user.name "github-actions[bot]"
        git add .
        git commit -m "Update generated code"
