name: PR Type

on:
  pull_request:
    types: [opened, edited, synchronize, reopened, labeled, unlabeled]

jobs:
  check_pull_request_type:
    name: Check for PR kind
    runs-on: ubuntu-latest
    steps:
      - uses: docker://agilepathway/pull-request-label-checker:latest
        with:
          one_of: kind/bug,kind/documentation,kind/feature,kind/regression,kind/refactor,kind/cleanup,kind/proposal,kind/chore
          repo_token: ${{ secrets.GITHUB_TOKEN }}
